name: aoc2025
version: 0.0.0
license: MIT
copyright: (c) 2025 Michael Adler
author: Michael Adler
maintainer: Michael Adler

ghc-options: -Wall

dependencies:
   - attoparsec
   - base
   - bytestring
   - matrix
   - unordered-containers
   - vector
   - disjoint-containers

default-extensions:
  - OverloadedStrings
  - MultilineStrings

executable:
  main: Main.hs
  source-dirs: app
  ghc-options:
    - -O2
  dependencies:
    - aoc2025

library:
  source-dirs: src

tests:
  spec:
    defaults: hspec/hspec@main
    dependencies: aoc2025
