name: aoc2025
version: 0.0.0
license: MIT
copyright: (c) 2025 Michael Adler
author: Michael Adler
maintainer: Michael Adler

ghc-options: -Wall

dependencies:
   - base
   - attoparsec
   - protolude
   - bytestring
   - unordered-containers
   - containers
   - directory
   - vector # Vector is a "better" Array
   - array # Arrays are not for the faint of heart
   - pretty-simple # just for debugging purposes
   - disjoint-containers # day 8
   - z3 # day 10, painful to use

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - MultilineStrings
  - TupleSections
  - LambdaCase

executable:
  main: Main.hs
  source-dirs: app
  ghc-options:
    - -O2
  dependencies:
    - aoc2025

library:
  source-dirs: src

tests:
  spec:
    defaults: hspec/hspec@main
    dependencies: aoc2025
